[project]
name = "gatana-client"
version = "0.1.2"
description = "A client library for accessing Gatana"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.23.0,<0.29.0",
    "attrs>=22.2.0",
    "python-dateutil>=2.8.0",
]

[tool.poetry]
name = "gatana-client"
version = "v1.4.3"
description = "A client library for accessing Gatana"
authors = []
readme = "README.md"
packages = [
    { include = "gatana_client" },
]
include = ["gatana_client/py.typed"]

[tool.poetry.dependencies]
python = "^3.10"
httpx = ">=0.23.0,<0.29.0"
attrs = ">=22.2.0"
python-dateutil = "^2.8.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["F", "I", "UP"]
